### PR TITLE
check transport connection

### PR DESCRIPTION
**Pull request by RyanKung**

### CODE REVIEW

**Comment by RyanKung** [comment]
* Issue:
If browsers disconnect / fresh page / reconnected, the transport in swarm table will be frozen in `Checking` status.

**Comment by RyanKung** [comment]
@googolmo plz check this commit `https://github.com/RingsNetwork/rings-node/pull/235/commits/74d330dc9718b19173cd5944283561ca674acb9a`

WASM test will fail if we check connection status while sending a message.

**Comment by googolmo** [comment]
@RyanKung this PR https://github.com/RingsNetwork/rings-node/pull/236 will make wasm test pass

**Comment by RyanKung** [comment]
> @RyanKung this PR #236 will make wasm test pass

Still not work

**Review by Ma233 — APPROVED** [review]
LGTM

**Review by googolmo — APPROVED** [review]

**Pull request merged**
